COBC_STANDARD_ARGUMENTS := -Wall -Werror
SOURCE_DIRECTORY := src
MAIN_PROGRAM     := $(SOURCE_DIRECTORY)/DVD-THING.CBL
SUBPROGRAMS      := $(SOURCE_DIRECTORY)/PLATFORM/TERMINAL-SIZE.POSIX.CBL $(SOURCE_DIRECTORY)/PLATFORM/CLEAR-TERMINAL.POSIX.CBL

vpath %.CBL $(dir $(MAIN_PROGRAM) $(SUBPROGRAMS))
MAIN_PROGRAM_OBJECT_FILE := $(notdir $(MAIN_PROGRAM:.CBL=.o))
SUBPROGRAM_OBJECT_FILES  := $(notdir $(SUBPROGRAMS:.CBL=.o))

cobol-dvd-thing.out: $(MAIN_PROGRAM_OBJECT_FILE) $(SUBPROGRAM_OBJECT_FILES)
	cobc $(COBC_STANDARD_ARGUMENTS) -x -o $@ $^
$(MAIN_PROGRAM_OBJECT_FILE): %.o: %.CBL
	cobc $(COBC_STANDARD_ARGUMENTS) -cx -o $@ $<
$(SUBPROGRAM_OBJECT_FILES): %.o: %.CBL
	cobc $(COBC_STANDARD_ARGUMENTS) -cm -o $@ $<

.PHONY: clean
clean:
	rm *.out *.o
